version: "3.9"

services: 
  mongo:
    image: mongo:4.4.4-bionic
    restart: unless-stopped
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
      - /mongo:/data/db
    ports: 
      - 27017:27017

  mongoExpress:
    image: mongo-express
    restart: always
    depends_on: 
      - mongo
    links:
      - mongo
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=randomString
      - ME_CONFIG_BASICAUTH_PASSWORD=randomString

